{
 "title": "2_O2_Generator",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Παροχή Νέας Γεννήτριας O2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Nm3/h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"O2_New_Gen_Flow\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Παροχή Νέας Γεννήτριας O2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Nm3/h" } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"O2_New_Gen_Flow\"\r\n  )\r\n|> aggregateWindow(every: 1m, fn: mean, createEmpty: true)"
    }
   ]
  },
  {
   "title": "ΚΑΤΑΝΑΛΩΣΗ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Nm3/h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"FLOW\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "ΚΑΤΑΝΑΛΩΣΗ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Nm3/h" } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"FLOW\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Πίεση Δοχείων Γεννήτριας",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"LBePr\"\r\n  )\r\n  |> last()"
    },
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"RBePr\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Πίεση Δοχείων Γεννήτριας",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"LBePr\"\r\n  )\r\n|> aggregateWindow(every: 1m, fn: mean, createEmpty: true)"
    },
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"RBePr\"\r\n  )\r\n|> aggregateWindow(every: 1m, fn: mean, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Πίεση BOOSTER",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"FILL_Pr\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Πίεση BOOSTER",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"FILL_Pr\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Θερμοκρασία  Χώρου",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"Amb_Temp\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Θερμοκρασία Χώρου",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"Amb_Temp\"\r\n  )\r\n|> aggregateWindow(every: 1m, fn: mean, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Πίεση Γεννήτριας",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"GENPr\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Πίεση Γεννήτριας",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"GENPr\"\r\n  )\r\n|> aggregateWindow(every: 1m, fn: mean, createEmpty: true)"
    }
   ]
  }
 ]
}