{
 "title": "New_O2_Generator",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Καθαρότητα Οξυγόνου",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"O2_Pur\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Καθαρότητα Οξυγόνου",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"O2_Pur\"\r\n  )"
    }
   ]
  },
  {
   "title": "Θερμοκρασία  Χώρου",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"Amb_Temp\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Θερμοκρασία Χώρου",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"Amb_Temp\"\r\n  )"
    }
   ]
  },
  {
   "title": "Πίεση Οξυγόνου Δίκτυο Α",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"O2_NtA\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Πίεση Οξυγόνου Δίκτυο Α",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"O2_NtA\"\r\n  )"
    }
   ]
  },
  {
   "title": "Switch Λειτουργίας",
   "type": "stat",
   "description": "Διακόπτης Λειτουργίας",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "columns": [
      { "selector": "field4", "text": "Buzzer", "type": "number" }
     ],
     "fields": [
      { "jsonPath": "", "name": "" }
     ],
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"Switch\"\r\n  )\r\n  |> last()",
     "query_mode": "standard",
     "root_selector": "feeds",
     "source": "url",
     "type": "json",
     "url": "https://api.thingspeak.com/channels/1287104/feeds.json?api_key=0UUXHNGR2C0GLO0Y",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "STATUS",
   "type": "stat",
   "description": "Διακόπτης Λειτουργίας",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "columns": [
      { "selector": "field4", "text": "Buzzer", "type": "number" }
     ],
     "fields": [
      { "jsonPath": "", "name": "" }
     ],
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"Status\"\r\n  )\r\n  |> last()",
     "query_mode": "standard",
     "root_selector": "feeds",
     "source": "url",
     "type": "json",
     "url": "https://api.thingspeak.com/channels/1287104/feeds.json?api_key=0UUXHNGR2C0GLO0Y",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Παροχή Νέας Γεννήτριας O2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Nm3/h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"O2_New_Gen_Flow\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Παροχή Νέας Γεννήτριας O2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Nm3/h" } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"O2_New_Gen_Flow\"\r\n  )"
    }
   ]
  },
  {
   "title": "Πίεση Δοχείων Αέρα",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"LBePr\"\r\n  )"
    },
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"RBePr\"\r\n  )"
    }
   ]
  },
  {
   "title": "Πίεση Δοχείων Γεννήτριας",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"LBePr\"\r\n  )"
    },
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"RBePr\"\r\n  )"
    }
   ]
  },
  {
   "title": "Switch Λειτουργίας",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 31 },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"kepware\" and\n    r._field == \"Switch\"\n  )\n  |> last()"
    }
   ]
  },
  {
   "title": "Switch Λειτουργίας",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 31 },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"kepware\" and\n    r._field == \"Switch\"\n  )\n  |> last()"
    }
   ]
  }
 ]
}