{
 "title": "New_O2_Generator",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Καθαρότητα Οξυγόνου",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"O2_Pur\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Καθαρότητα Οξυγόνου",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"O2_Pur\"\r\n  )"
    }
   ]
  },
  {
   "title": "Πίεση Οξυγόνου Δίκτυο Α",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"O2_NtA\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Πίεση Οξυγόνου Δίκτυο Α",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"O2_NtA\"\r\n  )"
    }
   ]
  },
  {
   "title": "Παροχή Νέας Γεννήτριας O2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Nm3/h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"O2_New_Gen_Flow\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Παροχή Νέας Γεννήτριας O2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Nm3/h" } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"O2_New_Gen_Flow\"\r\n  )"
    }
   ]
  }
 ]
}