{
 "title": "New_O2_Generator",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Καθαρότητα Οξυγόνου",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"O2_Pur\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Καθαρότητα Οξυγόνου",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"O2_Pur\"\r\n  )"
    }
   ]
  },
  {
   "title": "Πίεση Αεροσυμπιεστή",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"COMP\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Πίεση Αεροσυμπιεστή",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"COMP\"\r\n  )"
    }
   ]
  },
  {
   "title": "Πίεση Οξυγόνου Δίκτυο Α - ΓΕΝΝΗΤΡΙΑ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"O2_NtA\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Πίεση Οξυγόνου Δίκτυο Α",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"O2_NtA\"\r\n  )"
    }
   ]
  },
  {
   "title": "Πίεση Οξυγόνου Δίκτυο B - ΠΡΟΣ ΚΑΤΑΝΑΛΩΣΗ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"O2_NET_B\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Πίεση Οξυγόνου Δίκτυο Β - ΠΡΟΣ ΚΑΤΑΝΑΛΩΣΗ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"O2_NET_B\"\r\n  )"
    }
   ]
  },
  {
   "title": "Παροχή Νέας Γεννήτριας O2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Nm3/h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"O2_New_Gen_Flow\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Παροχή Νέας Γεννήτριας O2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"O2_New_Gen_Flow\"\r\n  )"
    }
   ]
  },
  {
   "title": "ΚΑΤΑΝΑΛΩΣΗ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Nm3/h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"FLOW\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "ΚΑΤΑΝΑΛΩΣΗ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"O2_New_Gen_Flow\"\r\n  )"
    }
   ]
  },
  {
   "title": "Πίεση Δοχείων Αέρα",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"LBePr\"\r\n  )\r\n  |> last()"
    },
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"RBePr\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Πίεση Δοχείων Γεννήτριας",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"LBePr\"\r\n  )"
    },
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"RBePr\"\r\n  )"
    }
   ]
  },
  {
   "title": "Πίεση BOOSTER",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"FILL_Pr\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Πίεση BOOSTER",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"FILL_Pr\"\r\n  )"
    }
   ]
  },
  {
   "title": "Θερμοκρασία  Χώρου",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"Amb_Temp\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Θερμοκρασία Χώρου",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"Amb_Temp\"\r\n  )"
    }
   ]
  },
  {
   "title": "Πίεση Γεννήτριας",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"GENPr\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Πίεση Γεννήτριας",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"GENPr\"\r\n  )"
    }
   ]
  },
  {
   "title": "Σημείο Δρόσου",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"Dew_Point\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Σημείο Δρόσου",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"Dew_Point\"\r\n  )"
    }
   ]
  },
  {
   "title": "Switch Λειτουργίας Γεννήτριας",
   "type": "stat",
   "description": "Διακόπτης Λειτουργίας",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "columns": [
      { "selector": "field4", "text": "Buzzer", "type": "number" }
     ],
     "fields": [
      { "jsonPath": "", "name": "" }
     ],
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"Switch\"\r\n  )\r\n  |> last()",
     "query_mode": "standard",
     "root_selector": "feeds",
     "source": "url",
     "type": "json",
     "url": "https://api.thingspeak.com/channels/1287104/feeds.json?api_key=0UUXHNGR2C0GLO0Y",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "STATUS",
   "type": "stat",
   "description": "Διακόπτης Λειτουργίας",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "columns": [
      { "selector": "field4", "text": "Buzzer", "type": "number" }
     ],
     "fields": [
      { "jsonPath": "", "name": "" }
     ],
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"Status\"\r\n  )\r\n  |> last()",
     "query_mode": "standard",
     "root_selector": "feeds",
     "source": "url",
     "type": "json",
     "url": "https://api.thingspeak.com/channels/1287104/feeds.json?api_key=0UUXHNGR2C0GLO0Y",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "ON HOURS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "columns": [
      { "selector": "field4", "text": "Buzzer", "type": "number" }
     ],
     "fields": [
      { "jsonPath": "", "name": "" }
     ],
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"Gen_On_time_Hours\"\r\n  )\r\n  |> last()",
     "query_mode": "standard",
     "root_selector": "feeds",
     "source": "url",
     "type": "json",
     "url": "https://api.thingspeak.com/channels/1287104/feeds.json?api_key=0UUXHNGR2C0GLO0Y",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "RUN HOURS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "columns": [
      { "selector": "field4", "text": "Buzzer", "type": "number" }
     ],
     "fields": [
      { "jsonPath": "", "name": "" }
     ],
     "query": "from(bucket: \"Kepware\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kepware\" and\r\n    r._field == \"Gen_Run_time_Hours\"\r\n  )\r\n  |> last()",
     "query_mode": "standard",
     "root_selector": "feeds",
     "source": "url",
     "type": "json",
     "url": "https://api.thingspeak.com/channels/1287104/feeds.json?api_key=0UUXHNGR2C0GLO0Y",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}